version: '3.4'

networks:
    dev:
        driver: bridge

services:
    kys-backend:
        image: docker.io/library/kysbackend
        depends_on:
            - app_db
        container_name: kysbackend-services
        ports:
            - "5000:80"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - "ConnectionStrings__DefaultConnection=User Id=postgres;Password=postgres;Server=app_db;Port=5432;Database=kysdb;IntegratedSecurity=true;Pooling=true;"
            - "ASPNETCORE_URLS=http://+:80"
        networks:
            - dev

    app_db:
        image: postgres:latest
        container_name: appdb-services
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_DB=kysdb"
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - app_data:/var/lib/postgresql/data
        networks:
            - dev

volumes:
    app_data:
